### ISSUE TITLE
New File Name Broken

### ISSUE THREAD

**Issue by Mohoganogan** [takyanagida/raw_nmea_logger#1]
Code currently does not create sequential file names after 00000 and 00001.  File for storing names keeps appending 00001 to the end of the existing number.

Causes only two total data files to every be created.  The second one then gets all data created.

**Comment by takyanagida** [comment]
I couldn't reproduce the issue with the following procedure.

- Prepare blank 16GB SD (formatted in FAT32)
- Turn on and off the power switch 3 times.
- See the SD with Explorer on Windows and 000002 is correctly written as attached image.

![20200305-GPSloggerTest](https://user-images.githubusercontent.com/1140847/75970080-3071c080-5f13-11ea-8f0d-afdceb54b69c.png)

**Comment by Mohoganogan** [comment]
I think this switch in code fixes it.


original:
lastnum_file = SD.open(LASTNUM_FILE, FILE_WRITE);

New:
lastnum_file = SD.open(LASTNUM_FILE, O_CREAT | O_WRITE);


changed both instances of “FILE_WRITE” to "O_CREAT | O_WRITE”



Sean Monaghen

**Comment by takyanagida** [comment]
According to the official SD.open document, available flags are FILE_READ and FILE_WRITE.

https://www.arduino.cc/en/Reference/SDopen

But thank for sharing the information, anyway.

**Comment by takyanagida** [comment]
I encountered the same issue after updating Arduino IDE.
SD.h specification seems changed somewhere. SD.h's current version I use is 1.2.4.

Fix is now commited as: https://github.com/takyanagida/raw_nmea_logger/commit/a6b1f686d4f741578094157dbe228157067fcf61
